# Generated by Django 4.1.7 on 2023-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'seq_num',
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name='№'
                    ),
                ),
                (
                    'order',
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name='заказ №'
                    ),
                ),
                (
                    'price_usd',
                    models.FloatField(
                        blank=True, max_length=10, null=True, verbose_name='стоимость,$'
                    ),
                ),
                (
                    'required_date',
                    models.DateField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name='срок поставки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
